### PR TITLE
Allow researchers to choose whether to use Double DQN

### PR DESCRIPTION
**Pull request by StephenArk30**
In my research, I need to compare the performance of modified DQN(double, dueling, ...) with the origin DQN (2013 and 2015), and I couldn't find a way to make the DQN "origin". So I add a param to control whether to use double DQN in DQN policy.

Please check if it's the right implementation.

### CODE REVIEW

**Comment by Trinkle23897** [comment]
Why not set target_update_freq=0?

**Comment by StephenArk30** [comment]
> Why not set target_update_freq=0?

I think target q network is from [DQN version 2015 (NIPS 2015)](https://web.stanford.edu/class/psych209/Readings/MnihEtAlHassibis15NatureControlDeepRL.pdf) but not Double DQN. The [DDQN paper](https://arxiv.org/pdf/1509.06461.pdf) also mentioned this.

The difference between DDQN and Nature DQN is that it uses the online network to get the best action, and uses target network to calculate Q. As the paper wrote:

> We therefore propose to evaluate the greedy policy according to the online network, but using the target network to estimate its value.

**Comment by Trinkle23897** [comment]
I see, the difference is target_q estimation. But only adding such an argument is kind of weird because DQNPolicy has many subclasses -- C51, QRDQN, DiscreteBCQ, ..., how about them related to this issue...?

**Comment by StephenArk30** [comment]
What about adding a DDQNPolicy?

**Comment by Trinkle23897** [comment]
Hmm... I need other's opinion. @danagi

**Review by Trinkle23897 — APPROVED** [review]

**Comment by p-veloso** [comment]
How do I access the tianshou version with DDQN? I installed the latest version/0.4.1 using

`pip install git+https://github.com/thu-ml/tianshou.git@master --upgrade 
`

What is confusing for me is that according to github 0.4.1 is the latest version. However, while the documentations for the master and latest versions have the argument is_double, the installation and documentation for 0.4.1 do not have it. How do I get a version with DDQN?

**Comment by Trinkle23897** [comment]
Hmm… my bad. Currently you need to directly install from master branch instead of a specific tagged version.

**Pull request merged**
