### PR TITLE
Use lower-level API to reduce overhead.

### LINKED ISSUE #96: Batch & Buffer profiling
Related to #95

### PR DESCRIPTION
**Pull request by duburcqa**
Related to https://github.com/thu-ml/tianshou/issues/96

### CODE REVIEW

**Comment by duburcqa** [comment]
@Trinkle23897 Ready to be merged ! Welcome performance comeback :smiley:

**Comment by Trinkle23897** [comment]
cool!

**Comment by Trinkle23897** [comment]
I'll merge one hour later (if you want to add more).

**Comment by duburcqa** [comment]
It should be OK now. I just noticed that some unit test were missing and added them. Feel free to merge when you want :+1:

**Comment by Trinkle23897** [comment]
A bug:
```python
In [1]: from tianshou.data import ReplayBuffer, Batch                                                                                                                                                               

In [2]: b = ReplayBuffer(size=10)                                                                                                                                                                                   

In [3]: b.add(1,1,1,1,1, {'a':3, 'b': {'c': 5}})                                                                                                                                                                    

In [4]: b                                                                                                                                                                                                           
Out[4]: 
ReplayBuffer(
    obs: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    act: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    rew: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    done: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    obs_next: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    info: Batch(
              a: array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
              b: Batch(
                     c: array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]),
                 ),
          ),
    policy: Batch(),
)
```
The `b.info.a` and `b.info.b.c` should be zero-initialized.

**Comment by duburcqa** [comment]
Why ? There is no unit test checking it and you are not supposed to access those data since you are ahead of the buffer index. I can easily fix it but for me it is not a bug if it is not part of the specifications (and hence checked by unit tests).

**Comment by Trinkle23897** [comment]
Yes, it's my fault not to add this script to unittest. 
Btw,
```python
In [6]: b[1]                                                                                                                                                                                                        
Out[6]: 
Batch(
    obs: 0,
    act: 0,
    rew: 0,
    done: 0,
    obs_next: 0,
    info: Batch(
              a: 3,
              b: Batch(
                     c: 5,
                 ),
          ),
    policy: Batch(),
)

In [7]: b[1].info.b.c                                                                                                                                                                                               
Out[7]: 5
```
I just want to keep all the syntax to be consistent: the obs is zero-init, so that the info batch should also be zero-init.

You can image a scenario: a user add info0, info2, info4, info6. At some time he wants to get info1, which should be `{}`. However, in this implementation, it will return info0.

**Comment by duburcqa** [comment]
Yes I understand your point, yet I'm not sure if zeroed yes better than None/nan (as I'm doing for partial item assignment of Batch). For now I did as you asked and added unit tests.

**Comment by Trinkle23897** [comment]
Hmm, I think None is better than zero.
But if we save `None` instead of zero, the numpy array will fall back to np.objects, which will possibly cause some performance issue (e.g. the alignment and indexing)...? I'm not sure.

**Comment by duburcqa** [comment]
> Hmm, I think None is better than zero.
But if we save None instead of zero, the numpy array will fall back to np.objects, which will possibly cause some performance issue (e.g. the alignment and indexing)...? I'm not sure.

Yes, that's why I'm using nan for `np.array` to avoid such issue.

**Comment by duburcqa** [comment]
So, I'm on it. I'll let you know when it is ready.

**Comment by duburcqa** [comment]
Done ! Here is the new behavior. Unit test included. (Note that only '0' is available for integer arrays since there is no such thing as nan/None for them).

```                                                                       
In [1]:    b = ReplayBuffer(size=10)                                                                                                                                                                       
In [2]:    b.add(1, 1, 1, 'str', 1, {'a': 3, 'b': {'c': 5.0}})                                                                                                                                             

In [2]:   b  
ReplayBuffer(
    obs: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    act: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    rew: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    done: array(['str', None, None, None, None, None, None, None, None, None],
                dtype=object),
    obs_next: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    info: Batch(
              a: array([3, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
              b: Batch(
                     c: array([ 5., nan, nan, nan, nan, nan, nan, nan, nan, nan]),
                 ),
          ),
    policy: Batch(),
)
```

**Comment by Trinkle23897** [comment]
And one more thing: it would be of great help if you add the new feature of `Batch` and `Buffer` into the documentation accordingly!

**Pull request merged**
