### PR TITLE
pettingzoo wrapper

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [x] new feature
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the code using `make commit-checks` (**required**)
- [x] If applicable, I have mentioned the relevant/related issue(s)
- [x] If applicable, I have listed every items in this Pull Request below

PR to follow the issue https://github.com/thu-ml/tianshou/issues/446

### CODE REVIEW

**Comment by jkterry1** [comment]
@Trinkle23897 could you please approve tests? I'm trying to fix the more obvious failures

**Comment by jkterry1** [comment]
@Trinkle23897 could you please approve again?

**Comment by mahi97** [comment]
I wondered whether this PR want to change tianshou so it only works with **pettingzoo environments** for multi-agent or we want to keep the support of **tianshou.MultiAgentEnv** too?

Current changes in **MultiAgentPolicyManager** remove the support for **tianshou.MultiAgentEnv**, and that is the reason the tests are failing.

**Comment by jkterry1** [comment]
My preference would be to specifically work for pettingzoo environments, its a pretty widely used standard (over 30 third party environments and like a dozen learning libraries use it as their primary API)

**Comment by mahi97** [comment]
I think the pettingzoo wrapper is ready to be used.
Should I open a new PR for this repository or `rodrigodelazcano:pettingzoo`?

**Comment by Trinkle23897** [comment]
> My preference would be to specifically work for pettingzoo environments

Agree!

> Should I open a new PR for this repository or rodrigodelazcano:pettingzoo?

I prefer the former.

**Comment by mahi97** [comment]
Ok, sure, I opened a new one: #494 .

**Pull request closed without merging**
