### PR TITLE
bugfixes: gym->gymnasium; render() update

### LINKED ISSUE #759: TypeError: render() takes 1 positional argument but 2 were given
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)

  0.4.10 0.25.2 1.12.1+cu113 1.21.6 3.7.15 (default, Oct 12 2022, 19:14:55) 
  [GCC 7.5.0] linux

  ```

New to `tianshou` and `pettingzoo` library, following tutorial: https://github.com/thu-ml/tianshou/blob/master/docs/tutorials/tictactoe.rst

Copy paste the two files:
1. https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/tic_tac_toe.py
2. https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/test_tic_tac_toe.py

Running
```
$ python test_tic_tac_toe.py
...
$ python test_tic_tac_toe.py --watch --resume-path log/tic_tac_toe/dqn/policy.pth --opponent-path log/tic_tac_toe/dqn/policy.pth

  File "/content/tic_tac_toe.py", line 240, in watch
    result = collector.collect(n_episode=1, render=args.render)
  File "/usr/local/lib/python3.7/dist-packages/tianshou/data/collector.py", line 354, in collect
    self.env.render()
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/venvs.py", line 355, in render
    return [w.render(**kwargs) for w in self.workers]
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/venvs.py", line 355, in <listcomp>
    return [w.render(**kwargs) for w in self.workers]
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/worker/dummy.py", line 49, in render
    return self.env.render(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tianshou/env/pettingzoo_env.py", line 150, in render
    return self.env.render(mode)
TypeError: render() takes 1 positional argument but 2 were given

```

### LINKED ISSUE #767: pettingzoo render have problem
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ *] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.10 0.26.2 1.10.2 1.20.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
Thanks to the developer for opening the source of this project. I have been using it for a while, and recently I'm using pettingzoo to build a private environment. Recently, pettingzoo was updated to PettingZoo == 1.22.1, and there was an error in rendering.

Use the test file [tictactoe.py](https://github.com/thu-ml/tianshou/blob/master/test/pettingzoo/tic_tac_toe.py)  provided by you, an error will be reported in the render link after the training is completed. The error is as follows:

  ```python
render() takes 1 positional argument but 2 were given
  ```

After investigation, it is because pettingzoo updated the input position of the render parameter.

Is there any good compatibility method?

### PR DESCRIPTION
**Pull request by WillDudley**
Credits (names from the Farama Discord):

- Reid
- Puckyle
- chattershuts

### CODE REVIEW

**Comment by WillDudley** [comment]
@Trinkle23897 PettingZoo*Tianshou tutorials are now live at https://pettingzoo.farama.org/tutorials/tianshou/beginner/

They pass CI, so there shouldn't be issues - if there  are, feel free to check the workflow at: https://github.com/Farama-Foundation/PettingZoo/blob/master/.github/workflows/linux-tutorials-test.yml

Or just pop me a ping :)

Hope this clears up any confusion!

**Comment by nrwahl2** [comment]
Reid == @nrwahl2 :)

Thanks, Will!

**Comment by Trinkle23897** [comment]
When I run `python test/pettingzoo/test_tic_tac_toe.py`:

```py
Traceback (most recent call last):
  File "test/pettingzoo/test_tic_tac_toe.py", line 21, in <module>
    test_tic_tac_toe(get_args())
  File "test/pettingzoo/test_tic_tac_toe.py", line 17, in test_tic_tac_toe
    watch(args, agent)
  File "/home/trinkle/github/tianshou-new/test/pettingzoo/tic_tac_toe.py", line 240, in watch
    result = collector.collect(n_episode=1, render=args.render)
  File "/home/trinkle/github/tianshou-new/tianshou/data/collector.py", line 354, in collect
    self.env.render()
  File "/home/trinkle/github/tianshou-new/tianshou/env/venvs.py", line 355, in render
    return [w.render(**kwargs) for w in self.workers]
  File "/home/trinkle/github/tianshou-new/tianshou/env/venvs.py", line 355, in <listcomp>
    return [w.render(**kwargs) for w in self.workers]
  File "/home/trinkle/github/tianshou-new/tianshou/env/worker/dummy.py", line 49, in render
    return self.env.render(**kwargs)
  File "/home/trinkle/github/tianshou-new/tianshou/env/pettingzoo_env.py", line 150, in render
    return self.env.render()
  File "/home/trinkle/.local/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 64, in render
    return super().render()
  File "/home/trinkle/.local/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 88, in render
    return self.env.render()
  File "/home/trinkle/.local/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 88, in render
    return self.env.render()
  File "/home/trinkle/.local/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 88, in render
    return self.env.render()
  File "/home/trinkle/.local/lib/python3.8/site-packages/pettingzoo/classic/tictactoe/tictactoe.py", line 231, in render
    gymnasium.logger.WARN(
TypeError: 'int' object is not callable
```

Also, can you add three links to tianshou's doc? Either create a subsection after multi-agent in cheatsheet, or just insert in that subsection
- https://pettingzoo.farama.org/tutorials/tianshou/beginner/
- https://pettingzoo.farama.org/tutorials/tianshou/intermediate/
- https://pettingzoo.farama.org/tutorials/tianshou/advanced/

**Comment by APN-Pucky** [comment]
Puckyle == @APN-Pucky

I think pettingzoo should maybe directly link/copy this very useful tianshou tutorial https://tianshou.readthedocs.io/en/master/tutorials/tictactoe.html#tic-tac-toe-environment.

**Review by Trinkle23897 — APPROVED** [review]

**Comment by WillDudley** [comment]
@Trinkle23897 Really sorry for the delay. I've just released 1.22.2 for PZ which deals with the WARN bug.

**Pull request merged**
