### PR TITLE
fix #99

### LINKED ISSUE #99: support for multiple updates in one step
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou/
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

I think it would be great if tianshou support for multiple network updates in one step. Acctually I found this need was often met and supported in other libraries. If you agree, I would like to submit a pull request to add this feature.

### PR DESCRIPTION
**Pull request by danagi**
- [ ] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [x] algorithm implementation fix
    + [ ] documentation modification
    + [ ] new feature
- [ ] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

### CODE REVIEW

**Comment by Trinkle23897** [comment]
What's your definition of `step` in trainer?

**Comment by danagi** [comment]
A global step or an algorithmic step, consist of collect step and update step. In other words, an epoch with `n` steps that has `m` collect  steps and `t` update steps, would collect total `n*m` frames and update network total `n*t` times.

**Comment by Trinkle23897** [comment]
Could you please add this to the documentation? Also within this definition, the code in onpolicy_trainer should be modified, could you please make them be consistent with each other?

**Comment by danagi** [comment]
Ok, no problem.

**Comment by Trinkle23897** [comment]
@danagi how's going on?

**Comment by danagi** [comment]
Sorry, I’ve got a lot to do. Give me some time please.

**Comment by danagi** [comment]
Ok, forget about this PR. I found out that in this definition, it's hard to duel with the code `for i in range(min(result['n/st'] // collect_per_step, t.total - t.n)):` in offtrainer and the code `for b in batch.split(batch_size):` in onpolicy algorithms. Because this two lines also update policy network but hard to re-explain in this definition. The previous verison which I mistakenly thought there was a bug in it, is much easier to understand. Sorry for taking your time.

**Pull request closed without merging**
