### PR TITLE
Dev: rebase master

### PR DESCRIPTION
**Pull request by youkaichao**
- [ ] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [ ] new feature
- [ ] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] and [issue categories] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, sys
  print(tianshou.__version__, torch.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue categories]: https://github.com/thu-ml/tianshou/projects/2
  [issue tracker]: https://github.com/thu-ml/tianshou/issues?q=

### CODE REVIEW

**Comment by Trinkle23897** [comment]
I have no idea how to solve the conflict. Since in #133 I use "rebase and merge", and GitHub uses its customized "rebase" command and changes the commit hash. I tried #148 and Kaichao tried #149 and this commit but we are not satisfied with the result.

I think there are two ways to solve it:
1. force push to master to revert the commit hash to be the same as `dev`. Need to re-tag `0.2.4.post1`.
2. merge master to dev (as this PR), but I think it may cause some other issues, for example, other PR based on old `dev` needs to resolve the conflict.

Maybe there is a third and better way?

And is it a must for the current `dev` branch? I look at other awesome repos on GitHub and they all use master instead of dev.

**Comment by youkaichao** [comment]
> merge master to dev (as this PR), but I think it may cause some other issues, for example, other PR based on old dev needs to resolve the conflict.

I tried in my local environment. Many conflicts.

> force push to master to revert the commit hash to be the same as dev. Need to re-tag 0.2.4.post1.

I vote for this. Since dev is our main branch and master is only used for release, it seems we can reset the head of master to the head of dev to avoid these annoying issues.

**Comment by duburcqa** [comment]
> force push to master to revert the commit hash to be the same as dev. Need to re-tag 0.2.4.post1.

I would rather avoid forcing `master` branch at all cost. Personally I force push `dev` branch instead after every merge on `master`. For now, just do a proper `rebase --onto` while rebasing `dev` on `master` to get only the new commits since the last release, force push `dev`, then merge `dev` on `master, then force push `dev` on new master. That's it.

**Comment by youkaichao** [comment]
I’m lost. 

> For now, just do a proper rebase --onto while rebasing dev on master to get only the new commits since the last release

The last release is v0.2.4.post1, and is the head of master now. So ``git rebase master`` is the same as ``git rebase master --onto v0.2.4.post1``.

We can do this on dev, but I think what @Trinkle23897 concerns is that this forced push in dev will make pull requests like #122 have many conflicts.

**Comment by duburcqa** [comment]
> The last release is v0.2.4.post1, and is the head of master now. So git rebase master is the same as git rebase master --onto v0.2.4.post1.

Absolutely not.

**Comment by duburcqa** [comment]
```
git rebase --onto upstream/master a55ad33 upstream/dev
```

And here you go ! Pretty easy, isn't it ?

The, force push the new `upstream/dev` branch, and your are good to go merging it on master. After that, do not forget to push force `dev` on `master` this time :smile:

**Comment by Trinkle23897** [comment]
> I vote for this. Since dev is our main branch and master is only used for release, it seems we can reset the head of master to the head of dev to avoid these annoying issues.

I don't like the way to treat master as a release-only branch. I found few repo do like this. The separation of master and dev has caused some extra problems for us in my opinion. So I'm here discussing this issue.

**Comment by Trinkle23897** [comment]
> ```
> git rebase --onto upstream/master a55ad33 upstream/dev
> ```
> 
> And here you go ! Pretty easy, isn't it ?
> 
> The, force push the new `upstream/dev` branch, and your are good to go merging it on master. After that, do not forget to push force `dev` on `master` this time

I'll try it but I don't know whether this will cause some extra conflicts with current unmerged PRs.
Seems like all is well.

**Comment by duburcqa** [comment]
> I don't like the way to treat master as a release-only branch. I found few repo do like this. 

Same here. `dev` should be use to increase flexibility and fast release of unstable PR. So far, we are not really using it this way.

> The separation of master and dev has caused some extra problems for us in my opinion. So I'm here discussing this issue.

I don't think so. We just need to get use of it. It is pretty easy to manage if done carefully.

**Comment by duburcqa** [comment]
> I'll try it but I don't know whether this will cause some extra conflicts with current unmerged PRs.
Seems like all is well.

No it should not. And if it is, it can always be fixed with a simple `rebase --onto`. So no big deal.

**Comment by Trinkle23897** [comment]
> > I'll try it but I don't know whether this will cause some extra conflicts with current unmerged PRs.
> > Seems like all is well.
> 
> No it should not. And if it is, it can always be fixed with a simple `rebase --onto`. So no big deal.

I tested and except for #143, other PRs have conflict. But I think these are no big deal too.

**Comment by duburcqa** [comment]
I'm done with the rebase on my PRs.

**Comment by Trinkle23897** [comment]
I still want to discuss this thing:
https://softwareengineering.stackexchange.com/a/312024
> Having worked with a develop branch for a year or two, just to have it merged into master every now and then, I can just say: amen, abandon that thing :] 

---

I think the first issue is that we cannot perform a documentation fix or a bug fix in time by using the dev branch.

If we merge the unstable PR into master instead of dev, users can checkout the tag like "0.2.4.post1" in git and readthedocs for both for the stable version.

**Comment by Trinkle23897** [comment]
> I still want to discuss this thing:
> https://softwareengineering.stackexchange.com/a/312024
> 
> > Having worked with a develop branch for a year or two, just to have it merged into master every now and then, I can just say: amen, abandon that thing :]
> 
> I think the first issue is that we cannot perform a documentation fix or a bug fix in time by using the dev branch.
> 
> If we merge the unstable PR into master instead of dev, users can checkout the tag like "0.2.4.post1" in git and readthedocs for both for the stable version.

I withdraw what I have said above. Current test_drqn fails on cuda device, and if it appears in the master, some users may get annoyed. This is more important.

**Comment by duburcqa** [comment]
And anyway, it is impossible to rely only on unit tests to make sure everything is working properly. Having new features available on dev branch first during a few weeks is a good way to ensure that everything gets heavily tested before releasing them on master. Patching master must be avoided at all cost for credible projects.

**Comment by Trinkle23897** [comment]
I think my issue can be solved at https://tianshou.readthedocs.io/en/dev/

**Comment by duburcqa** [comment]
> I think my issue can be solved at https://tianshou.readthedocs.io/en/dev/

Awesome ! For me it is the way to go without any doubt.

**Pull request closed without merging**
