### PR TITLE
Pull from thu-ml/tianshou

### PR DESCRIPTION
**Pull request by gohsyi**
- [ ] I have marked all applicable categories:
    + [x] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [ ] new feature
- [ ] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [ ] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, sys
  print(tianshou.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue tracker]: https://github.com/thu-ml/tianshou/projects/2

### CODE REVIEW

**Comment by Trinkle23897** [comment]
?

**Comment by gohsyi** [comment]
Sorry it’s a mistake, please just ignore it.

**Comment by Trinkle23897** [comment]
So have you made the pong_ppo work?

**Comment by gohsyi** [comment]
Not yet, working on it too.

**Comment by Trinkle23897** [comment]
I have updated the ppo algorithm in the last few commits, you can check it out and sync to your repo.

**Comment by gohsyi** [comment]
Great, that’s exactly what I want. Sorry to create a false pull request. Maybe you can help remove it?

**Comment by heartInsert** [comment]
@gohsyi  
Hey ,mate , it seems  that   you  are  working   on   pong_ppo.py  . 
 I    am  trying  to  adapt   "ppo"  in  discrete ,  but   I  find  it  hard  to  converge   in   " tianshou/test/discrete/pong_ppo.py ". Have   you  already  made  it work ?

**Comment by Trinkle23897** [comment]
> I am trying to adapt "ppo" in discrete , but I find it hard to converge in " tianshou/test/discrete/pong_ppo.py ". Have you already made it work ?

Sorry about that, please refer to #272.

**Pull request closed without merging**
