### PR TITLE
fix conda support and keep API compatibility

### PR DESCRIPTION
**Pull request by Trinkle23897**
https://github.com/conda-forge/tianshou-feedstock/pull/13

Add nni test in CI pipeline, only runs in GPU_test

### CODE REVIEW

**Comment by ultmaster** [comment]
Thanks. Glad to see an integration test of nni!

I'll see if I can make this more elegant and neat, in case some changes of our internal APIs break tianshou's test in future.

**Comment by Trinkle23897** [comment]
Let me know if nni's current CI pipeline works or not with 0.4.6.post1 version via pip install.

**Comment by ultmaster** [comment]
> Let me know if nni's current CI pipeline works or not with 0.4.6.post1 version via pip install.

The problem is resolved. Thank you so much.

**Comment by Trinkle23897** [comment]
The nni test fails again: https://github.com/thu-ml/tianshou/actions/runs/3125052390/jobs/5069025377
cc @ultmaster

**Comment by ultmaster** [comment]
> The nni test fails again: https://github.com/thu-ml/tianshou/actions/runs/3125052390/jobs/5069025377 cc @ultmaster

Fixed in #750.

**Pull request merged**
