### PR TITLE
Added pre-commit

### PR DESCRIPTION
**Pull request by Markus28**
- This PR adds the checks that are defined in the Makefile as pre-commit hooks.
- Hopefully, the checks are equivalent to those from the Makefile, but I can't guarantee it. 
- CI remains as it is.
- As I pointed out on discord, I experienced some conflicts between flake8 and yapf, so it might be better to transition to some other combination (e.g. black).

### CODE REVIEW

**Comment by Markus28** [comment]
Sorry, I ran the wrong python version. It appears mypy isn't happy on Python 3.7. I added the ignore hints back.

**Comment by Markus28** [comment]
I needed to add some new `type: ignore` because the mypy version changed for CI. This should also fix the CI for other PRs (e.g. the PettingZoo one). It might be a good idea to pin the mypy version.

**Comment by Trinkle23897** [comment]
I'd like to remove mypy in pre-commit because it has inconsistent behaviors with different python version and os, which will block contributors living in non py38+ubuntu2004

**Review by Trinkle23897 — APPROVED** [review]

**Comment by nuance1979** [comment]
I support the transition from `yapf` to `black`. I personally find `black` more consistent with code formatting.

**Comment by Trinkle23897** [comment]
agree

**Pull request merged**
