### PR TITLE
Do not check bounds since it is always valid when everything is fine.

### LINKED ISSUE #90: Batch to Numpy compatibility
The current implementation of `__len__` and `__getitem__` is kind of weird because it is infinitely recursive: one can do `Batch()[0]` and it does not throw an exception but rather return the same object `Batch()`. This is an issue because it breaks the compatibility with standard numpy methods such as `np.mean`, `np.max` ... which should work otherwise. It would be easy to change this behavior, but many policy algorithm relies on it.  Calling such a numpy method simply hangs infinitely, for example using `np.asarray(Batch())`, and so does `[o for o in Batch(a=[1.0])]` which is even worst.

I opened a PR implementing the desired behavior, but I need help to update accordingly the policy algorithms.

______

Here is what you get using the proposed implementation.

Input:
```
np.mean(Batch(a=np.array([[1.0, 2.0], [3.0, 4.0]]), b=np.array([5.0, 6.0])))
```
Output:
```
Batch(
    a: array([2., 3.]),
    b: 5.5,
)
```

### LINKED ISSUE #96: Batch & Buffer profiling
Related to #95

### PR DESCRIPTION
**Pull request by duburcqa**
Avoid the overhead of checking bounds for subfields since it should be fine useless the user is messing up terribly somewhere else.

### CODE REVIEW

**Comment by Trinkle23897** [comment]
Simple solution, I like it!

**Comment by Trinkle23897** [comment]
Hmm... I didn't figure out what's the bottleneck. Still 8 mins per unittest.
The seed is fixed so that the training process would be exactly the same as the previous version.

**Comment by duburcqa** [comment]
Do you have any idea how we could profile the code ? Perhaps Batch is supporting too many types, requiring many `isinstance` check for each of them. 8 minutes on your computer or github ? Because sometimes github slow down for some reason.

**Comment by Trinkle23897** [comment]
On GitHub. But in my computer, it is almost the same as previous. I'll open an issue about profiling Batch.

**Pull request merged**
