### PR TITLE
Prioritized DQN

### PR DESCRIPTION
**Pull request by rocknamx8**
- [ ] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [x] new feature
- [ ] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [x] I have visited the [source website], and in particular read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, sys
  print(tianshou.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/thu-ml/tianshou
  [known issues]: https://github.com/thu-ml/tianshou/#faq-and-known-issues
  [issue tracker]: https://github.com/thu-ml/tianshou/projects/2

### CODE REVIEW

**Comment by Trinkle23897** [comment]
Thanks for your contributions! Could you please follow the rule in [https://tianshou.readthedocs.io/en/latest/contributing.html](https://tianshou.readthedocs.io/en/latest/contributing.html)? I'll review the code later.

**Comment by rocknamx8** [comment]
Wait for minute ˊ_>ˋ

**Comment by Trinkle23897** [comment]
Could you please add another test with prioritized DQN? (BTW, why did you delete the segtree.py?)

**Comment by rocknamx8** [comment]
OK, I'll add a test to it.
I got something wrong at the beginning, so this is a stochastic prioritization replay implementation, not the greedy ones and may no need for sum tree. 
It seems that numpy is faster enough in sampling even in million scale buffer size.
I haven't implemented the rank-based variant, it will take some time :(

**Pull request merged**
