### PR TITLE
Improve data loading from D4RL and convert RL Unplugged to D4RL format

### PR DESCRIPTION
**Pull request by nuance1979**
- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [x] new feature
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the code using `make commit-checks` (**required**)
- [x] If applicable, I have mentioned the relevant/related issue(s)
- [x] If applicable, I have listed every items in this Pull Request below

Improve data loading from D4RL and convert RL Unplugged data to D4RL format following the [discussion](https://github.com/thu-ml/tianshou/pull/621#discussion_r862363574).

### CODE REVIEW

**Comment by nuance1979** [comment]
@Trinkle23897 I will make the change in all `d4rl_*.py` and `atari_*.py` files once you are ok with this PR.

**Comment by Trinkle23897** [comment]
> @Trinkle23897 I will make the change in all `d4rl_*.py` and `atari_*.py` files once you are ok with this PR.

Sure, please go ahead.

**Comment by Trinkle23897** [comment]
How about using a function in `utils.py` so that we don't need to change it everywhere?

**Comment by nuance1979** [comment]
> How about using a function in `utils.py` so that we don't need to change it everywhere?

Sure. I can do that.

**Review by Trinkle23897 — APPROVED** [review]

**Pull request merged**
