### PR TITLE
Docs/overhaul

### LINKED ISSUE #916: Turn tutorials into notebooks that are then executed in CI
Thin involves at least

- [x] Copy all notebooks from drive to a new folder in repo called `notebooks`
- [x] Adjust notebooks to current state of tianshou (using master)
- [x] Include `nbstripout` and `black[jupyter]` into lint and format
- [x] Prepare jupyter-book build compatible with tianshou styles and logo
- [x] Execute jupyter-book as part of CI
- [x] Include the built book in the docs built by sphinx (also in CI)

Additional:
- [x] Look into binder/colab integration with the notebooks now being in the repo
- [x] Extend notebooks and fix typos if needed
- [ ] Make mypy check notebooks, if possible

### PR DESCRIPTION
**Pull request by MischaPanch**
Closes #916 

This PR presents an overhaul of how the docs are built and presented

1. Notebooks are no longer just links in some drive. They are checked in without their outputs, executed in CI, and thereby serve as integration tests as well as tutorials. They have been adjusted to work with the current master branch
2. Execution of notebooks is cached, so it's very fast
3. The api docs are generated automatically with a custom script. Previously this was only done for the highlevel module
4. The build is happening with jupyter-book (which still uses sphinx in the backend). It is using the default jupyter book theme, which I think looks very nice and adds useful navigation to the right side of the screen
5. Customized api docs rendering for better appearance
6. The toc of the docs is built automatically with jupyter-book. The api docs generation script has been adjusted accordingly
7. The viewcode and linkcode extensions add source code and links to it to the docs
8. A bunch of docstrings have been adjusted to better reflect the configured rules
9. Several typing issues improved to make mypy happy

It was quite a piece of work, I hope you like the result :)

### CODE REVIEW

**Comment by MischaPanch** [comment]
@carlocagnetta Here the PR for the docs, I fixed the problems with the api docs and added a whole lot of convenience layers on top (like fully automated toc and api docs generation).

I had to rebuild a new branch since you branched off an older version that is no longer compatible with master (b/c of commit squashing)

The only thing missing is to make the build work in readthedocs. Lokally, `poe doc-build` runs through and produces beatiful documentation :)

@Trinkle23897

We set up a readthedocs account for demo purposes, but have to figure out how to make the build work with jupyter book's extensions. Shoudn't be too hard. Otherwise, this is done from our point of  view. If you want to have a look already, you can just pull the branch and call `poe doc-clean && poe doc-build`

**Comment by MischaPanch** [comment]
I now see that there are some typing issues, maybe some ignored rules were accidentally deleted from pyproject. Will look into it asap

**Comment by MischaPanch** [comment]
@opcode81 Have a look, if you want to. If you like this style, we could use a similar setup for sensai

**Comment by Trinkle23897** [comment]
Is there an online link for preview? Also I can give you current rtd permission if you want

**Comment by MischaPanch** [comment]
> Is there an online link for preview? Also I can give you current rtd permission if you want

Working on having it run in rtd - it's a painful journey. Almost done, I think, then I'll post the link for preview.

My rtd profile name is MischaPanch, associtated to my GH account. Could you give me access to tianshou's official rtd project?

**Comment by MischaPanch** [comment]
Finally, the rtd build worked! Here

https://tianshou-fork.readthedocs.io/en/latest/

**Comment by MischaPanch** [comment]
I now see that the notebook outputs were not added, gonna fix that tomorrow

**Comment by Trinkle23897** [comment]
love it, just added you to official rtd maintainer. there's an email need to click for accepting invitation

**Comment by nuance1979** [comment]
> Finally, the rtd build worked! Here
> 
> https://tianshou-fork.readthedocs.io/en/latest/

Looks great! However, the API docs do not show up. Is that expected?

**Comment by MischaPanch** [comment]
@Trinkle23897 

Completely done now, see  https://tianshou-fork.readthedocs.io/en/latest/

Notebooks are executed and the api docs are also working fine. Had to dive deeper into rtd-docker-poetry stuff than I ever wanted to.

@opcode81 helped in improving the task running, making them platform independent

I force pushed and cleaned the history. I'd merge this without squashing after the checkmark, if that's ok.

**Comment by MischaPanch** [comment]
> > Finally, the rtd build worked! Here
> > https://tianshou-fork.readthedocs.io/en/latest/
> 
> Looks great! However, the API docs do not show up. Is that expected?

They do now

**Comment by MischaPanch** [comment]
Note that the main page for the api docs is empty, since the toc is displayed to the left and I didn't want to duplicate the pages for modules as well as init files. But if you go to the page of one of the modules, you get

https://tianshou-fork.readthedocs.io/en/latest/03_api/data/batch.html

Note the link to the source code, which is also uploaded to the docs and rendered there

**Comment by MischaPanch** [comment]
I improved the API docs landing page now, will be built in about 20 mins. Added a subtitle and displayed links to direct children, like for all subpackages

**Review by nuance1979 — APPROVED** [review]
LGTM. Great work!

**Pull request merged**
