### PR TITLE
Changelog + dependabot bumps

### PR DESCRIPTION
**Pull request by MischaPanch**

### CODE REVIEW

**Comment by MischaPanch** [comment]
@ChenDRAG @Trinkle23897 Pinged you as reviewers b/c it seems like I still can't merge to master - could you adjust the rules pls? You could either add an exception for me (not sure if it's possible in GH), or bump the permissions for all maintainers (unless you want to bump my overall permissions to the repo again ;) ).

It would be good if I could merge things like this one, quick bug fixes, or small changes to the docs without review. All other things can pass the usual review process.

PS: With the current permissions, I can't override the always-squash-commits rule, which is also unfortunate (and was the original reason for giving me admin rights in the first place):

image

**Review by ChenDRAG — APPROVED** [review]
done. I'm working on it to see if it is possible.

**Comment by MischaPanch** [comment]
@ChenDRAG I still can't merge b/c my last commit (fixing a typo) skipped the expensive CI, and I can't override the branch protection checks. Could you pls press the merge button? 

Thanks for looking into the permissions issue!

**Comment by Trinkle23897** [comment]
Screenshot 2024-04-25 at 8 51 38 AM
I did the trick in branch protection rule setting, not sure if that's enough

**Comment by MischaPanch** [comment]
Thanks @Trinkle23897 , I'll check out in the next PR and will ping you if the permissions are still lacking

**Comment by ChenDRAG** [comment]
It's okay. I've changed Michael's role. No need for this now,

**Pull request merged**
