### PR TITLE
Fixed hardcoded reward_treshold

### LINKED ISSUE #547: reward_threshold is better to be as argument for the test scripts
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
In test_cql.py there is a hardcoded part of the code to the task "Pendulum-v1":

```python
  if args.task == 'Pendulum-v1':
      env.spec.reward_threshold = -1200  # too low?
```
Better to have an argument `parser.add_argument('--reward_treshold', type=float, default=-1200)` and set it up `env.spec.reward_threshold = args.reward_threshold`

I can make a pull request for this if you agree.

### PR DESCRIPTION
**Pull request by BFAnas**
Close #547

### CODE REVIEW

**Comment by Trinkle23897** [comment]
Could u please go through all `test/**.py` and `examples/**.py`?

**Comment by BFAnas** [comment]
> 

Ok working on it!

**Comment by BFAnas** [comment]
I'm also copying the comments from here:
```python
env.spec.reward_threshold = -1100  # too low?
```
to here:
```python
parser.add_argument('--reward_threshold', type=float, default=-1100) # too low?
```

**Comment by Trinkle23897** [comment]
1. do not overwrite env.spec.reward_threshold; for stop_fn use args.reward_threshold instead
2. `"--reward_threshold"` -> `"--reward-threshold"` in args to keep consistency

**Comment by BFAnas** [comment]
Done! Please tell me if anything needs to be changed

**Comment by Trinkle23897** [comment]
test/discrete, test/continuous, test/modelbased, examples/atari/, examples/box2d/, examples/vizdoom

```bash
$ grep reward_threshold examples test -r
```

**Comment by BFAnas** [comment]
I'm almost done, but I noticed this in test_psrl.py:
```python
if args.task == "NChain-v0":
    reward_threshold = 3400
    # reward_threshold = 3647  # described in PSRL paper
else:
    reward_threshold = None
```
Meaning that it is a deliberate choice to have the reward threshold hardcoded. It makes sense since it is closely related to the task. And the risk with the fix I suggested is that it's possible to change the task without changing the reward threshold, which will lead to some bugs that can be hard to debug.
What do you think? we leave it as it is or do you have a suggestion?

**Comment by Trinkle23897** [comment]
```python
parser.add_argument("--reward-threshold", type=float, default=None)

if args.reward_threshold is None:
  default_reward_threshold = {"CartPole-v0": 195, "NChain-v0": 3400}
  args.reward_threshold = default_reward_threshold.get(args.task)
```

**Comment by BFAnas** [comment]
Done! Please check and let me know if anything else needs to be changed.

**Comment by BFAnas** [comment]
I made a correction, `default_reward_threshold.get(args.reward_threshold)` should be `default_reward_threshold.get(args.task)`. The tests locally run correctly, except for Pendulum-v1 my gym complains that it only knows Pendulum-v0

**Comment by Trinkle23897** [comment]
> The tests locally run correctly, except for Pendulum-v1 my gym complains that it only knows Pendulum-v0

`pip install gym --upgrade`

**Comment by BFAnas** [comment]
Using something else than gym==0.19.0 misses my environment, and it's a hustle to make a new one with mujoco especially, and cuda and other stuff. I prefer to leave it in peace now and use Pendulum-v0.

**Comment by Trinkle23897** [comment]
Ok. I'll check the detail after finishing today's exam...

**Comment by BFAnas** [comment]
Good luck with the exam 🥇

**Review by Trinkle23897 — APPROVED** [review]

**Pull request merged**
