### PR TITLE
Show progress

### PR DESCRIPTION
**Pull request by michalgregor**
Hi, I added support for disabling the tqdm progress bar in the base trainer by replacing it with a dummy class that just keeps track of the total and n stats, but doesn't display progress.

I wonder whether you would like to merge this.

* A dummy_tqdm class added to utils: it replicates the interface used
  by trainers, but does not show the progress bar;
* Added a show_progress argument to the base trainer: when
  show_progress == True,  dummy_tqdm is used in place of tqdm;

Btw. I wonder whether requiring `make format` and then not actually doing it on every commit  is a good idea – I think it is going to make the changes I made more difficult to find – but at least I did that step in a separate commit, so that should help.

- [ ] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [X] new feature
- [X] I have reformatted the code using `make format` (**required**)
- [X] I have checked the code using `make commit-checks` (**required**)
- [X] If applicable, I have mentioned the relevant/related issue(s)
- [X] If applicable, I have listed every items in this Pull Request below

### CODE REVIEW

**Comment by Trinkle23897** [comment]
Did you use the old version isort?
I use isort 5.9.3, yapf 0.31.0, python3.8, ubuntu 2004

**Comment by Trinkle23897** [comment]
Why not use `disable`? https://stackoverflow.com/a/61109243/8773993

**Comment by michalgregor** [comment]
Disable does not seem to work – not the way we are using the interface here. With disabled, n does not get incremented when doing update:

```
if self.disable:
            return

        if n < 0:
            self.last_print_n += n  # for auto-refresh logic to work
        self.n += n
```

https://github.com/tqdm/tqdm/blob/master/tqdm/std.py

**Comment by michalgregor** [comment]
> Did you use the old version isort? I use isort 5.9.3, yapf 0.31.0, python3.8, ubuntu 2004

I think you are right! I assumed it was among the packages updated automatically by the script. I will make sure my versions are as close to yours as possible. What should I do then? Do I need to rerun ``make format`` and ``make commit-checks`` with them?

**Comment by Trinkle23897** [comment]
`pip3 install isort yapf --upgrade`

See the version here: https://github.com/thu-ml/tianshou/runs/6470112919?check_suite_focus=true (Install dependencies)

```
Collecting yapf
  Downloading yapf-0.32.0-py2.py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 37.8 MB/s eta 0:00:00
Collecting isort
  Downloading isort-5.10.1-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 22.3 MB/s eta 0:00:00
```

**Comment by Trinkle23897** [comment]
> Disable does not seem to work – not the way we are using the interface here. With disabled, n does not get incremented when doing update:

```diff
         # perform n step_per_epoch
         with progress(
-            total=self.step_per_epoch, desc=f"Epoch #{self.epoch}", **tqdm_config
+            total=self.step_per_epoch, desc=f"Epoch #{self.epoch}", **tqdm_config, disable=True
         ) as t:
```

I manually tested with `disable=True` and `dummy_tqdm`. I didn't find any difference between these two approaches.

**Comment by michalgregor** [comment]
Are you sure you are in fact running the disable=True on the tqdm version and not the dummy version? Because for me, with disable=True, episodes never terminate – which is what I would expect with t.n not getting updated.

**Comment by Trinkle23897** [comment]
Yes you're right. I'll take it.

**Review by Trinkle23897 — APPROVED** [review]

**Pull request merged**
