### PR TITLE
Fix clip when action_space is provided

### PR DESCRIPTION
**Pull request by liuliu**
Thie clip method in BasePolicy fixed to -1.0, 1.0. For Humanoid, its
control range is between -0.4, 0.4, it won't clip correctly. This PR
fixed that problem.

- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [x] algorithm implementation fix
    + [ ] documentation modification
    + [ ] new feature
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the code using `make commit-checks` (**required**)
- [ ] If applicable, I have mentioned the relevant/related issue(s)
- [ ] If applicable, I have listed every items in this Pull Request below

### CODE REVIEW

**Review by Trinkle23897 — APPROVED** [review]

**Comment by Trinkle23897** [comment]
Oops, I guess it's not an easy fix, since the raw action from nn could be mostly [-1, 1] and the action_space range can be various.

**Comment by liuliu** [comment]
> Oops, I guess it's not an easy fix, since the raw action from nn could be mostly [-1, 1] and the action_space range can be various.

Yeah, I didn't look at other experiments, for MuJoCo related ones, seems Humanoid-PPO run fine with the new range. Others all have range between [-1, 1].

**Comment by Trinkle23897** [comment]
How about InvertedPendulum `[-3, 3]` and Pusher `[-2, 2]`?

**Comment by liuliu** [comment]
> How about InvertedPendulum `[-3, 3]` and Pusher `[-2, 2]`?

Sorry, I think that I made a mistake when reading your code. It doesn't impact PPO at all because after clip, we did `action_scaling`. Hence, with this PR, InvertedPendulum and Pusher will fail on assertion at line 180. I am under the impression this is not the right fix. Do you think we should care about cases where `action_scaling = False`?

**Pull request closed without merging**
