### PR TITLE
Implement Decision Transformer for offline RL

### PR DESCRIPTION
**Pull request by nuance1979**
- [x] I have marked all applicable categories:
    + [ ] exception-raising fix
    + [ ] algorithm implementation fix
    + [ ] documentation modification
    + [x] new feature
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the code using `make commit-checks` (**required**)
- [x] If applicable, I have mentioned the relevant/related issue(s)
- [x] If applicable, I have listed every items in this Pull Request below

#626 Per discussion, this PR should be merged **after** the problem in collector is resolved.

### CODE REVIEW

**Comment by ChenDRAG** [comment]
I have a little suggestion. Maybe we shouldn't put decision transformer network architecture into net/common.py because this code is used by no other algorithms but dt. Transformers is still rarely used in rl for now (especially in online).  I'm not sure whether it's worth that much maintenance effort in the future given that much code?

Update:
Sorry, I didn't notice that the transformer code actually comes from a third-party library. This reduces a lot code implementation effort and is more acceptable.

**Comment by MischaPanch** [comment]
What's the status of this? Would be nice to have DT as part of the library. @nuance1979 do you have time to continue on this PR, in particular resolve the conflicts to master?

**Comment by nuance1979** [comment]
> What's the status of this? Would be nice to have DT as part of the library. @nuance1979 do you have time to continue on this PR, in particular resolve the conflicts to master?

This PR is abandoned because it is most likely not correct until we fix the RNN issues in `tianshou`. At one point, I tried to investigate and potentially fix the RNN issue but couldn't finish the job. The heart of the problem, I believe, is that the current way ReplayBuffer is sampled is not compatible with efficient RNN computation. However, I don't have spare time to work on it anymore. Feel free to close it.

**Comment by MischaPanch** [comment]
> This PR is abandoned because it is most likely not correct until we fix the RNN issues in `tianshou`. At one point, I tried to investigate and potentially fix the RNN issue but couldn't finish the job. The heart of the problem, I believe, is that the current way ReplayBuffer is sampled is not compatible with efficient RNN computation. However, I don't have spare time to work on it anymore. Feel free to close it.

Thanks for the answer! I'll keep it open, and once the RNN issues are fixed, it might either be continued or used as inspiration for a new attempt at decision transformers

**Comment by MischaPanch** [comment]
Closing, the changes to tianshou until this is feasible again will be too massive

**Pull request closed without merging**
